name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Setup android NDK
      id: setup-ndk
      # You may pin to the exact commit or the version.
      # uses: nttld/setup-ndk@dbacc5871a0fac6eef9a09d2ca86bc8bf79432c3
      uses: nttld/setup-ndk@v1.3.1
      with:
        ndk-version: r21e
        local-cache: true
    
    - name: Install qt
      uses: jurplel/install-qt-action@v3
      with:
        host: linux
        target: android
        arch: 'android'
        version: '5.15.2'
        modules: 'qtcharts'
    - name: build
      run: |
        ls -la
        echo ndk home $ANDROID_NDK_HOME
        qmake CONFIG+=release -spec android-clang
        make qmake_all
        ls -la
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
