name: iOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install qt
        uses: jurplel/install-qt-action@v3
        with:
          host: mac
          target: ios
          version: '5.15.2'
          modules: 'qtcharts'
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          mkdir builddir
          cd builddir
          qmake .. -spec macx-ios-clang CONFIG+=release CONFIG+=iphoneos CONFIG+=device IOS_TEAM_ID=Z45PLKLTHM
          make qmake_all
          make -j5
          cd nymea-app
          #xcodebuild build -project nymea-app.xcodeproj -scheme nymea-app -configuration Release  -destination generic/platform=iOS -destination-timeout 1  ENABLE_ONLY_ACTIVE_RESOURCES=NO
          xcodebuild -project nymea-app.xcodeproj -scheme nymea-app -archivePath nymea-app.xcarchive archive

