name: Ubuntu Touch CI

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  ubuntu_click:
    name: Ubuntu click package
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: setup build environment
      run: |
        sudo add-apt-repository ppa:bhdouglass/clickable
        sudo apt-get update
        sudo apt-get install clickable
    - name: build
      run: |
        ls -la
        sed -i "s/\"version\": \"[0-9\.]*\"/\"version\": \"`head -n 1 version.txt`\"/" packaging/ubuntu/click/manifest.json
        clickable build --skip-review --arch armhf
        clickable build --skip-review --arch arm64
        ls -la
    - name: archive artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: Ubuntu click armhf
        path: build/*/app/io.guh.nymeaapp_*.click
