on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  ubuntu_click:
    name: Ubuntu click package
    runs-on: ubuntu-22.04
    steps:
    - name: setup build environment
      run: |
        sudo apt install docker.io adb git python3 python3-pip python3-setuptools
        pip3 install --user clickable-ut
    - name: build
      run: |
        clickable
